AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  サンプルSAMテンプレート - Go言語用

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        TEST_ENV_1: ""
        TEST_ENV_2: ""
        TEST_ENV_3: ""

Resources:
  Api1Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/app1/
      Handler: main
      Runtime: go1.x
      Events:
        Api1Proxy:
          Type: Api
          Properties:
            Path: /api1 # APIのエンドポイントパス
            Method: any # HTTPメソッド

  Api2Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/app2/
      Handler: main
      Runtime: go1.x
      Events:
        Api2Proxy:
          Type: Api
          Properties:
            Path: /api2 # APIのエンドポイントパス
            Method: any # HTTPメソッド

Outputs:
  Api1FunctionUrl:
    Description: "API 1 URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/api1"
  Api2FunctionUrl:
    Description: "API 2 URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/api2"
